---

- name: Converge
  hosts: all
  become: true

  vars_files:
    - ../default/vars.yml
    - ../default/vars-db.yml
  vars:
    moodle_domain_name: "moodleupdate.test"  # We override this for the test

  pre_tasks:
    - name: Import Moodle PHP Setup role to set the web server config
      import_role:
        name: ansible-role-moodle
        tasks_from: phpsql-setup
      tags: install
    - name: Set Moodle version to 3.8.1 to update it later
      set_fact:
        moodle_version: "v3.8.1"
  roles:
    # Finally the role under test
    - name: ansible-role-moodle
  tasks:
    - name: Check the state of current moodle
      check_moodle:
        install_dir: "{{ moodle_src_path }}"
      become: true
      become_user: "{{ moodle_webserver_user }}"
      register: moodle_state_v381
    - name: Check the version of moodle is the right one
      assert:
        that:
          - "moodle_state_v381.current_release  == '3.8.1 (Build: 20200113)'"
          - "not moodle_state_v381.moodle_needs_upgrading|bool"
    - name: Update moodle to v3.8.2
      include_role:
        name: ansible-role-moodle
      vars:
        moodle_version: "v3.8.2"
