---
dependency:
  name: galaxy
  options:
    role-file: molecule-requirements.yml
driver:
  name: docker
platforms:
  - name: instanceupdate
    image: "calllearning/${MOLECULE_DISTRO:-ubuntu}-mysql-moodle-ansible:${MOLECULE_DISTRO_VERSION:-2204}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    etc_hosts: "{'moodle.test':  '127.0.0.1'}"
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: ../default/verify.yml
verifier:
  name: ansible
scenario:
  name: update
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
#    - side_effect
    - verify
    - destroy
