---
- hosts: all

  vars_files:
    - vars.yml
    - vars-db.yml

  roles:
    - call_learning.moodle

  tasks:
    - name: Trigger installation
      command: /bin/true
      notify: install moodle
      changed_when: false

    - name: Trigger installation
      command: /bin/true
      notify: update moodle
      changed_when: false
