---
language: python
services: docker

env:
  global:
    - ROLE_NAME: moodle
  matrix:
    - MOLECULE_DISTRO=centos MOLECULE_DISTRO_VERSION=8
    - MOLECULE_DISTRO=ubuntu MOLECULE_DISTRO_VERSION=1804
    - MOLECULE_DISTRO=debian MOLECULE_DISTRO_VERSION=10

before_install:
  # Upgrade Docker to work with docker-py.
  - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash

install:
  # Install test dependencies.
  - pip install molecule===3.0.6 yamllint ansible-lint flake8 nose docker

script:
  # Run tests  - default scenario then postgres and update scenarios
  - molecule test --all
  - nosetests library/test_check_moodle.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
