---
language: python
services: docker

env:
  global:
    - ROLE_NAME: moodle
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule ansible-lint docker flake8 yamllint nose

script:
  # Run tests.
  - molecule test
  - nosetests -library/test_check_moodle.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
