---
language: python
services: docker

env:
  global:
    - ROLE_NAME: moodle
  matrix:
    - MOLECULE_DISTRO=centos MOLECULE_DISTRO_VERSION=8
    - MOLECULE_DISTRO=ubuntu MOLECULE_DISTRO_VERSION=1804
    - MOLECULE_DISTRO=debian MOLECULE_DISTRO_VERSION=10

install:
  # Install test dependencies.
  - pip install molecule ansible-lint docker flake8 yamllint nose

script:
  # Run tests  - default scenario then posgres and update scenarios
  - molecule test --all
  - nosetests -library/test_check_moodle.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
