- name: Check and Manage Moodle Installation
  hosts: all
  gather_facts: false
  become: true
  vars:
    moodletool_local_path: "./files/moodletool.php"  # Local path to the moodletool.php file

  tasks:
    - name: Deploy moodletool.php to the Moodle CLI directory
      copy:
        src: "moodletool.php" # "{{ moodletool_local_path }}"
        dest: "{{ moodle_src_path }}/admin/cli/moodletool.php"
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Verify if config.php exists (manual check)
      command: /bin/bash -c 'test -f /srv/moodle/src/config.php && echo exists || echo missing'
      register: manual_check

    - name: Debug manual check result
      debug:
        var: manual_check.stdout
      
    - name: Check Moodle status
      moodle_status:
        install_dir: "{{ moodle_src_path }}"
      register: moodle_status

    - name: Debug Moodle status
      debug:
        var: moodle_status

    - name: Show Moodle status
      debug:
        msg: >
          Moodle Installed: {{ moodle_status.moodle_is_installed }}
          Needs Upgrading: {{ moodle_status.moodle_needs_upgrading }}
          Current Version: {{ moodle_status.current_version }}
          Current Release: {{ moodle_status.current_release }}
