---

- name: Prebuild Image - Mysql
  hosts: all
  become: true

  vars_files:
    - ../../defaults/main.yml
    - vars.yml
    - vars-mysql.yml

  pre_tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
  roles:
    # Database install
    # https://github.com/geerlingguy/ansible-role-mysql/issues/422
    - name: geerlingguy.mysql
    # And Git
    - name: geerlingguy.git
