---

# Usual tweaks and php mandatory packages for Moodle
# We don't use any of these tasks in the role itself as
# this is only a tool here to be used in other playbook like:
# - import_role: call-learning.moodle
#      tasks_from: phpsql-setup.yml
#      tags: install


#
# Global Packages
#

# Debian
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Add specific packages for Debian
  apt:
    pkg:
      - python-crontab
      - cron
      - python-pymysql
    state: present
  when: ansible_distribution == "Debian"

# Redhat and Centos

- name: Tweak Redhad/Centos package names
  block:
    - name: Set Mysql Packages For Redhat/Centos
      set_fact:
        mysql_packages:
          - mariadb
          - mariadb-server
          - mysql-libs
          - python2-PyMySQL
          - python3-PyMySQL
          - perl-DBD-MySQL
        mysql_daemon: mariadb
        mysql_log_error: /var/log/mariadb/mariadb.log
        mysql_syslog_tag: mariadb
  when: ansible_os_family == 'RedHat'

- name: Add specific packages for Redhat/Centos
  yum:
    name: crontabs
    state: present
  when: ansible_os_family == 'RedHat'

- name: Define postgresql_version to 9.3 for RedHat/CentOS.
  set_fact:
    postgresql_version: "9.3"
  when: ansible_os_family == "RedHat"

# ALL Systems
- name: Install dependencies.
  package: name={{ item }}
  with_items:
    - curl
    - unzip
    - sendmail

#
# PHP Packages
#

# ALL Distribution (note the difference in name from Debian and Ubuntu, version prefixing)
- name: Set php_packages for all distributions
  block:
    # We use PHP 7.2 for testing (see vars.yml and php-versions role)
    - name: Set php packages to an empty list and php_prefix
      set_fact:
        php_packages: []
        php_prefix: php
    - name: Set Php package prefix for Debian like systems
      set_fact:
        php_prefix: "php{{ php_version }}"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Set all php packages names
      set_fact:
        php_packages: "{{ php_packages }} + [ '{{ php_prefix }}-{{ item }}' ]"
      loop:
        - cli
        - common
        - curl
        - gd
        - intl
        - json
        - mbstring
        - opcache
        - readline
        - soap
        - xml
        - xmlrpc
        - zip
        - fpm
        - cli
        - ldap
        - solr
        - redis

- name: Add APCU package for debian / Ubuntu
  set_fact:
    php_packages: "{{ php_packages }} + ['php-apcu']"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Need to add php-process on Redhat so we can use moodle moosh
- name: Set php_packages (apcu + php-process) for PHP CentOS/Redhat from REMI package.
  set_fact:
    php_packages: "{{ php_packages }} + ['php-pecl-apcu', 'php-process']"
  when: ansible_os_family == "RedHat"

- name: Set php_package for postgres
  set_fact:
    php_packages: "{{ php_packages }} + ['{{ php_prefix }}-pgsql']"
  when: dbengine == 'postgres'

- name: Set php_package for MySQL
  set_fact:
    php_packages: "{{ php_packages }} + ['{{ php_prefix }}-mysql']"
  when: dbengine == 'mysql'
