---

# Usual tweaks and php mandatory packages for Moodle
# We don't use any of these tasks in the role itself as
# this is only a tool here to be used in other playbook like:
# - import_role: call_learning.moodle
#      tasks_from: phpsql-setup.yml
#      tags: install


#
# Global Packages
#

# Debian
- name: Update apt cache.
  apt:
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Add specific packages for Debian
  apt:
    pkg:
      - python3-crontab
      - cron
      - python3-pymysql
    state: present
  when: ansible_distribution == "Debian"

# Redhat and Centos
- name: Tweak Redhad/Centos package names
  block:
    - name: Set Mysql Packages For Redhat/Centos
      set_fact:
        mysql_packages:
          - mariadb
          - mariadb-server
          - mysql-libs
          - python2-PyMySQL
          - python3-PyMySQL
          - perl-DBD-MySQL
        mysql_daemon: mariadb
        mysql_log_error: /var/log/mariadb/mariadb.log
        mysql_syslog_tag: mariadb
  when: ansible_os_family == 'RedHat'

- name: Add specific packages for Redhat/Centos
  yum:
    name: crontabs
    state: present
  when: ansible_os_family == 'RedHat'

- name: Define postgresql_version to 9.3 for RedHat/CentOS.
  set_fact:
    postgresql_version: "9.3"
  when: ansible_os_family == "RedHat"

# ALL Systems
- name: Install dependencies.
  package: name={{ item }}
  with_items:
    - curl
    - unzip
    - sendmail

#
# PHP Packages
#

# ALL Distribution (note the difference in name from Debian and Ubuntu, version prefixing)
- name: Set php_packages for all distributions
  block:
    - name: Set Php package prefix for Debian like systems
      set_fact:
        php_prefix: "php{{ php_version }}"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Set all php packages names
      set_fact:
        php_packages:
          - "{{ php_prefix }}-cli"
          - "{{ php_prefix }}-common"
          - "{{ php_prefix }}-curl"
          - "{{ php_prefix }}-gd"
          - "{{ php_prefix }}-intl"
          - "{{ php_prefix }}-json"
          - "{{ php_prefix }}-mbstring"
          - "{{ php_prefix }}-opcache"
          - "{{ php_prefix }}-readline"
          - "{{ php_prefix }}-soap"
          - "{{ php_prefix }}-xml"
          - "{{ php_prefix }}-xmlrpc"
          - "{{ php_prefix }}-zip"
          - "{{ php_prefix }}-fpm"
          - "{{ php_prefix }}-cli"
          - "{{ php_prefix }}-ldap"
          - "{{ php_prefix }}-solr"
          - "{{ php_prefix }}-redis"
          - "{{ php_prefix }}-apcu"

# Need to add php-process on Redhat so we can use moodle moosh
- name: Set php_packages (apcu + php-process) for PHP CentOS/Redhat from REMI package.
  set_fact:
    php_packages: "{{ php_packages + ['php-pecl-apcu', 'php-process'] }}"
  when: ansible_os_family == "RedHat"

- name: Set php_package for postgres
  set_fact:
    php_packages: "{{ php_packages + [ (php_prefix + '-pgsql') ] }}"
  when: dbengine == 'postgres' or ( install_all_db_php_modules is defined and install_all_db_php_modules )

- name: Set php_package for MySQL
  set_fact:
    php_packages: "{{ php_packages + [ (php_prefix + '-mysql') ] }}"
  when: dbengine == 'mysql' or ( install_all_db_php_modules is defined and install_all_db_php_modules )
