---
# Here we assume that composer has been installed
# See https://github.com/geerlingguy/ansible-role-composer for the role to install composer

# This defines the usual path if not defined. We need to have an
# absolute path here as Redhat/Centos don't look at /usr/local/bin for binaries
- name: Define composer path to the default value if not defined
  set_fact:
    composer_path: "/usr/local/bin/composer"
  when: composer_path is undefined

- name: Check if composer is installed
  command: "{{ composer_path }} --version"
  register: composer_installed
  failed_when: composer_installed.rc != 0
  changed_when: false

- name: Check if Moosh is installed
  stat: "path={{ moosh_install_directory }}"
  register: moosh_dir_status

- name: Moosh - get from repository and install or update
  block:
    - name: Moosh - clone repository
      git:
        repo: "{{ moosh_repository }}"
        dest: "{{ moosh_install_directory }}"
        version: "{{ moosh_branch  |default(omit) }}"
        update: true
        depth: 1
      changed_when: false
    - name: Moosh - Install moosh dependencies
      command: "{{ composer_path }} install"
      args:
        chdir: "{{ moosh_install_directory }}"
      changed_when: false
  when: not moosh_dir_status.stat.exists

- name: Make sure all moosh files belongs to the web user
  file:
    path: "{{ moosh_install_directory }}"
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    mode: "u=rwx,g=rx,o=rx"
    recurse: true

# Note that the best place would be /usr/local/bin on Debian like system
# But unfortunately the apache user has only /usr/bin in its path
- name: Moosh - link to Moosh binary
  file:
    src: "{{ moosh_install_directory }}/moosh.php"
    dest: /usr/bin/moosh
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    state: link
  changed_when: false
