---

- name: Create config if it does not exist
  template:
    src: config.php.j2
    dest: "{{ moodle_src_path }}/config.php"
    mode: 0644
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    backup: true  # Take a backup just in case

# This is using our custom module to check moodle state
- name: Check the state of current moodle
  check_moodle:
    install_dir: "{{ moodle_src_path }}"
  become: true
  become_user: "{{ moodle_webserver_user }}"
  register: moodle_state

- name: Install Moodle
  include_tasks: commands/moodle-install.yml
  when: not moodle_state.moodle_is_installed|bool

# Change password to make sure we are always in sync
# Watch out this will work on Moodle where the reset_password.php command accepts arguments
# Added the cache purge as sometimes old users are cached when db is replaced
- name: Change admin password
  import_tasks: commands/moodle-resetpw.yml
  when: moodle_state.moodle_is_installed|bool

- name: Launch update (if needed)
  import_tasks: commands/moodle-update.yml
  when: moodle_state.moodle_is_installed|bool
    and moodle_state.moodle_needs_upgrading|bool

- name: Setup cron
  cron:
    name: "Moodle Cron"
    minute: "{{ moodle_cron_periodicity }}"
    job: "php {{ moodle_src_path }}/admin/cli/cron.php 2>&1"
    user: "{{ moodle_webserver_user }}"
  when: moodle_cron_periodicity is defined and moodle_cron_periodicity != 0
