---

- name: Tools - do file dump
  import_tasks: commands/moodle-filedump.yml
  tags: ['never', 'task-filedump']

- name: Tools - do a database dump
  import_tasks: commands/moodle-datadump.yml
  tags: ['never', 'task-datadump']

- name: Tools - Retrieve the latest code on the given branch (including submodules)
  import_tasks: commands/moodle-fetchsources.yml
  tags: ['never', 'task-fetchsource', 'task-updatecode']

- name: Tools - Update Moodle
  import_tasks: commands/moodle-update.yml
  tags: ['never', 'task-updatecode']

- name: Tools - Change admin password
  import_tasks: commands/moodle-resetpw.yml
  tags: ['never', 'task-updatepassword']

- name: Tools - Bootstrap Search SOLR
  import_tasks: commands/moodle-bootstrapsolr.yml
  tags: ['never', 'task-bootstrapsolr']

- name: Tools - Setup SOLR config in Moodle
  import_tasks: commands/moodle-setupsolr.yml
  tags: ['never', 'setup-solr']
