---
- import_tasks: setup-moosh.yml

- name: Tools - do data file dump
  block:
    - name: Archive data folder
      archive:
        path:
          - "{{ moodle_sitedata.shared_data_folder }}"
          - "{{ moodle_sitedata.local_data_folder }}"
        dest: /tmp/moodledata.tar.gz
    - name: Fetch archive
      fetch:
        src: /tmp/moodledata.tar.gz
        flat: true
        dest: dumps/moodledata-{{ inventory_hostname }}.{{ ansible_date_time.epoch }}.tar.gz
    - name: Delete Archive
      file:
        state: absent
        path: /tmp/moodledata.tar.gz
  tags: ['never', 'task-filedump']

- name: Tools - Retrieve the latest code on the given branch (including submodules)
  git:
    repo: "{{ moodle_git_url }}"
    dest: "{{ moodle_src_path }}"
    version: "{{ moodle_version }}"
    depth: 1  # Only shallow cloning. Can be fixed if needed later to have the full history (git pull --unshallow)
    key_file: "{{ moodle_git_key_file }}"
    recursive: true
    update: true
  become: true
  become_user: "{{ moodle_webserver_user }}"  # Check out as www-data
  notify:
    - upgrade moodle
  tags: ['never', 'task-updatecode']

- name: Tools - Change admin password
  command: chdir="{{ moodle_src_path }}" {{ item }}
  loop:
    - php admin/cli/purge_caches.php
    - php admin/cli/reset_password.php --username="{{ moodle_site_admin.username }}"
      --password="{{ moodle_site_admin.password }}"
  become: true
  become_user: "{{ moodle_webserver_user }}"
  changed_when: false
  tags: ['never', 'task-updatepassword']

- name: Tools - Bootstrap Search SOLR
  include_tasks: commands/moodle-bootstrapsolr.yml
  tags: ['never', 'task-bootstrapsolr']

- name: Tools - Setup SOLR config in Moodle
  include_tasks: commands/moodle-setupsolr.yml
  tags: ['never', 'setup-solr']
