---

- name: Converge
  hosts: all
  become: true

  vars_files:
    - ../default/vars/vars.yml
    - vars/vars-db.yml
  pre_tasks:
    - name: Import Moodle PHP Setup role to set the web server config
      import_role:
        name: call_learning.moodle
        tasks_from: phpsql-setup
      tags: install
  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    # Apache
    - name: geerlingguy.apache
    # PHP
    - name: geerlingguy.php-versions
    - name: geerlingguy.php
    # Then PHP Database libraries
    - name: geerlingguy.php-pgsql
    # PHP FPM
    - name: geerlingguy.apache-php-fpm
    # Other dependencies such as composer
    - name: geerlingguy.composer
    # Finally the role under test
    - name: call_learning.moodle
