---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - ../default/vars/vars.yml
    - vars/vars-db.yml
  pre_tasks:
    - name: Load distro-specific vars if available
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] }}.yml"
          paths:
            - vars
          skip: true

    - name: Import Moodle PHP Setup role to set the web server config
      import_role:
        name: call_learning.moodle
        tasks_from: phpsql-setup
      tags: install
  tasks:
    - name: Apply Molecule pre-support-role distro specifics
      include_tasks: ../default/tasks/include-distro-specifics.yml
      vars:
        molecule_distro_specific_dir: "{{ playbook_dir }}/../default/distro-specifics"
        molecule_distro_specific_phase: converge-before-support-roles
      tags: molecule-idempotence-notest

    - name: Install Molecule support roles
      block:
        - name: geerlingguy.repo-remi
          import_role:
            name: geerlingguy.repo-remi
          when: ansible_facts["os_family"] == 'RedHat'

        - name: geerlingguy.git
          import_role:
            name: geerlingguy.git

        - name: geerlingguy.apache
          import_role:
            name: geerlingguy.apache

        - name: geerlingguy.postgresql
          import_role:
            name: geerlingguy.postgresql

        - name: geerlingguy.php
          import_role:
            name: geerlingguy.php

        - name: geerlingguy.php-pgsql
          import_role:
            name: geerlingguy.php-pgsql

        - name: geerlingguy.apache-php-fpm
          import_role:
            name: geerlingguy.apache-php-fpm
      tags: molecule-idempotence-notest

    - name: Apply Molecule pre-role distro specifics
      include_tasks: ../default/tasks/include-distro-specifics.yml
      vars:
        molecule_distro_specific_dir: "{{ playbook_dir }}/../default/distro-specifics"
        molecule_distro_specific_phase: converge-before-role
      tags: molecule-idempotence-notest

    - name: Flush handlers before running the Moodle role
      meta: flush_handlers

    - name: Wait for PostgreSQL to accept connections
      wait_for:
        host: 127.0.0.1
        port: 5432
        timeout: 60

    # Finally the role under test
    - name: call_learning.moodle
      import_role:
        name: call_learning.moodle

    - name: Apply Molecule post-role distro specifics
      include_tasks: ../default/tasks/include-distro-specifics.yml
      vars:
        molecule_distro_specific_dir: "{{ playbook_dir }}/../default/distro-specifics"
        molecule_distro_specific_phase: converge-after-role
      tags: molecule-idempotence-notest
