---

- name: Verify
  hosts: all
  become: true

  vars:
    files_to_check:
      - "{{ moodle_src_path }}"
      - "{{ moodle_dataroot }}"
      - "{{ moodle_localcachedir }}"
      - "{{ moodle_tempdir }}"
      - "{{ moodle_sharedcachedir }}"
      - "{{ moodle_src_path }}/config.php"
  vars_files:
    - ../default/vars.yml
    - vars-db.yml

  pre_tasks:
    - name: Import Moodle PHP Setup role to set the web server config
      import_role:
        name: ansible-role-moodle
        tasks_from: configure-vars.yml

  tasks:
    - name: Check that all directories and files have been created
      include_tasks: ../default/tools/check-exists.yml
      loop: "{{ files_to_check }}"

    - name: Get Moodle current configuration
      check_moodle:
        install_dir: "{{ moodle_src_path }}"
      become: true
      become_user: "{{ moodle_webserver_user }}"
      register: moodle_state

    - name: Check that Moodle is installed
      assert:
        that: moodle_state.moodle_is_installed

    - name: Check that Moodle has the right version
      assert:
        that:
          - "moodle_state.current_release == '3.8.2 (Build: 20200309)'"

    - name: Get the site frontpage
      action: uri url=http://moodlepg.test return_content=yes
      register: webpage

    - name: Check that the page contains
      assert:
        that:
          - "'<h1>Moodle Test Site</h1>' in webpage.content"
