---
# Handle moodle installation (i.e. the setup process). We assume here that the config.php has been set and is valid
- name: installer
  listen: install moodle
  include_tasks: commands/moodle-install.yml

# Handle moodle upgrade if needed
- name: upgrader
  listen: upgrade moodle
  include_tasks: commands/moodle-update.yml

- name: Change admin password
  listen: reset moodle admin password
  include_tasks: commands/moodle-resetpw.yml
