---

- name: Verify
  hosts: all
  become: true

  vars_files:
    - ../default/vars.yml
    - ../default/vars-db.yml

  tasks:
    - name: Check the state of current moodle
      check_moodle:
        install_dir: "{{ moodle_src_path }}"
      become: true
      become_user: "{{ moodle_webserver_user }}"
      register: moodle_state
