---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vars/vars-db.yml
  pre_tasks:
    - name: Import Moodle PHP Setup role to set the web server config
      import_role:
        name: call_learning.moodle
        tasks_from: phpsql-setup
      tags: install
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
      tags: molecule-idempotence-notest
    - name: geerlingguy.git
      tags: molecule-idempotence-notest
    # Apache
    - name: geerlingguy.apache
      tags: molecule-idempotence-notest
    # Mysql
    - name: geerlingguy.mysql
      tags: molecule-idempotence-notest
    # PHP
    - name: geerlingguy.php-versions
      tags: molecule-idempotence-notest
    - name: geerlingguy.php
      tags: molecule-idempotence-notest
    # Then PHP Database libraries
    - name: geerlingguy.php-mysql
      tags: molecule-idempotence-notest
    # PHP FPM
    - name: geerlingguy.apache-php-fpm
      tags: molecule-idempotence-notest
    # Finally the role under test
    - name: call_learning.moodle
  post_tasks:
       - name: Restart php{{ php_version }}-fpm
         service:
           name: php{{ php_version }}-fpm
           state: restarted
           enabled: yes
         changed_when: false

