---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vars/vars-db.yml
  pre_tasks:
    - name: Import Moodle PHP Setup role to set the web server config
      import_role:
        name: call_learning.moodle
        tasks_from: phpsql-setup
      tags: install
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - name: geerlingguy.git
    # Apache
    - name: geerlingguy.apache
    # Mysql
    - name: geerlingguy.mysql
    # PHP
    - name: geerlingguy.php-versions
    - name: geerlingguy.php
    # Then PHP Database libraries
    - name: geerlingguy.php-mysql
    # PHP FPM
    - name: geerlingguy.apache-php-fpm
    # Other dependencies such as composer
    - name: geerlingguy.composer
    # Finally the role under test
    - name: call_learning.moodle
  post_tasks:
       - name: Restart php{{ php_version }}-fpm
         service:
           name: php{{php_version }}-fpm
           state: restarted
           enabled: yes

