---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: "calllearning/${MOLECULE_DISTRO:-ubuntu}-mysql-moodle-ansible:${MOLECULE_DISTRO_VERSION:-1804}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    etc_hosts: "{'moodle.test':  '127.0.0.1'}"
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  name: default
verifier:
  name: ansible
