---
dependency:
  name: galaxy
  options:
    role-file: molecule-requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "calllearning/${MOLECULE_DISTRO:-ubuntu}-mysql-moodle-ansible:${MOLECULE_DISTRO_VERSION:-2204}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    etc_hosts: "{'moodle.test':  '127.0.0.1'}"
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
