---
- hosts: all

  vars_files:
    - vars.yml

  pre_tasks:
    - include: setup.yml

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.postgresql
    - geerlingguy.php-pgsql
    - geerlingguy.git
    - role_under_test

  tasks:
    - name: Trigger installation
      command: /bin/true
      notify: install moodle
      changed_when: false

    - name: Trigger installation
      command: /bin/true
      notify: update moodle
      changed_when: false
