---
- hosts: all

  vars_files:
    - test-vars.yml

  pre_tasks:
    - include: test-setup.yml

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.postgresql
    - geerlingguy.php-pgsql
    - geerlingguy.git
    - role_under_test

  tasks:
    - name: Moodle - Trigger installation
      command: /bin/true
      notify: install moodle

    - name: Moodle - Trigger installation
      command: /bin/true
      notify: update moodle
