---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Install dependencies.
  package: name={{ item }}
  with_items:
    - curl
    - unzip
    - sendmail

- name: Set php_packages for all distributions
  block:
    # We use PHP 7.2 for testing (see vars.yml and php-versions role)
    - set_fact:
        php_packages: []
    - set_fact:
        php_prefix: php7.2
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - set_fact:
        php_packages: "{{ php_packages }} + [ '{{ php_prefix }}-{{ item }}' ]"
      loop:
        - cli
        - common
        - curl
        - gd
        - intl
        - json
        - mbstring
        - opcache
        - pgsql
        - readline
        - soap
        - xml
        - xmlrpc
        - zip
        - fpm
        - cli
        - ldap
        - solr
        - redis

- name: Add APCU package for debian / Ubuntu
  set_fact:
    php_packages: "{{ php_packages }} + ['php-apcu']"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Need to add php-process so we can use moodle moosh
- name: Set php_packages (apcu + php-process) for PHP CentOS/Redhat from REMI package.
  set_fact:
    php_packages: "{{ php_packages }} + ['php-pecl-apcu', 'php-process']"
  when: ansible_os_family == "RedHat"

- name: Define postgresql_version to 9.3 for RedHat/CentOS.
  set_fact:
    postgresql_version: "9.3"
  when: ansible_os_family == "RedHat"

- name: Set php_package for postgres
  set_fact:
    php_packages: "{{ php_packages }} + ['{{ php_prefix }}-pgsql']"
  when: dbengine == 'postgres'

- name: debug
  debug:
    msg: "System {{ moodle_database }} "

- name: Set php_package for mysql
  block:
    - set_fact:
        php_packages: "{{ php_packages }} + ['{{ php_prefix }}-mysql']"
    - set_fact:
        moodle_database: "{{ moodle_database | combine({ 'dbtype': 'mariadb'}) }}"
  when: dbengine == 'mysql'

- name: Tweak Centos package names
  block:
    - set_fact:
        mysql_packages:
          - mariadb
          - mariadb-server
          - mariadb-libs
          - MySQL-python
          - perl-DBD-MySQL
    - set_fact:
        mysql_daemon: mariadb
    - set_fact:
        mysql_log_error: /var/log/mariadb/mariadb.log
    - set_fact:
        mysql_syslog_tag: mariadb
    - set_fact:
        mysql_syslog_tag: /var/run/mariadb/mariadb.pid
  when: ansible_os_family == 'RedHat'

# https://blogs.oracle.com/jsmyth/apparmor-and-mysql
# We need a way to disable apparmor for mysql

## Specific for debian 9: we need to install mariadb at least 10.3
## as previous version are not compatible with moodle 3.0+

- name: Add repository for MariaDB (Debian) and set packages to mariadb
  block:
    - apt:
        pkg:
          - apt-utils
          - dirmngr
          - software-properties-common
        state: present
    - apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc
        state: present
    - apt_repository:
        repo: deb [arch=amd64,i386,ppc64el] http://mirrors.dotsrc.org/mariadb/repo/10.4/debian stretch main
        state: present
    - set_fact:
        mysql_packages:
          - mariadb-client
          - mariadb-server
  when: ansible_distribution == "Debian" and ansible_distribution_release == "stretch"
