---

#
# Global Packages
#

# Debian
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Add specific packages for Debian
  apt:
    pkg:
      - python-crontab
      - cron
      - python-pymysql
    state: present
  when: ansible_distribution == "Debian"

# Redhat and Centos

- name: Tweak Centos package names
  block:
    - set_fact:
        mysql_packages:
          - mariadb
          - mariadb-server
          - mysql-libs
          - python2-PyMySQL
          - python3-PyMySQL
          - perl-DBD-MySQL
    - set_fact:
        mysql_daemon: mariadb
    - set_fact:
        mysql_log_error: /var/log/mariadb/mariadb.log
    - set_fact:
        mysql_syslog_tag: mariadb
    - set_fact:
        mysql_syslog_tag: /var/run/mariadb/mariadb.pid
  when: ansible_os_family == 'RedHat'

- name: Add specific packages for Redhat/Centos
  yum:
    name: crontabs
    state: present
  when: ansible_os_family == 'RedHat'

- name: Define postgresql_version to 9.3 for RedHat/CentOS.
  set_fact:
    postgresql_version: "9.3"
  when: ansible_os_family == "RedHat"

# ALL Systems
- name: Install dependencies.
  package: name={{ item }}
  with_items:
    - curl
    - unzip
    - sendmail

#
# PHP Packages
#

# ALL Distribution (note the difference in name from Debian and Ubuntu, version prefixing)
- name: Set php_packages for all distributions
  block:
    # We use PHP 7.2 for testing (see vars.yml and php-versions role)
    - set_fact:
        php_packages: []
    - set_fact:
        php_prefix: php
    - set_fact:
        php_prefix: php7.2
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - set_fact:
        php_packages: "{{ php_packages }} + [ '{{ php_prefix }}-{{ item }}' ]"
      loop:
        - cli
        - common
        - curl
        - gd
        - intl
        - json
        - mbstring
        - opcache
        - pgsql
        - readline
        - soap
        - xml
        - xmlrpc
        - zip
        - fpm
        - cli
        - ldap
        - solr
        - redis

- name: Add APCU package for debian / Ubuntu
  set_fact:
    php_packages: "{{ php_packages }} + ['php-apcu']"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Need to add php-process on Redhat so we can use moodle moosh
- name: Set php_packages (apcu + php-process) for PHP CentOS/Redhat from REMI package.
  set_fact:
    php_packages: "{{ php_packages }} + ['php-pecl-apcu', 'php-process']"
  when: ansible_os_family == "RedHat"

- name: Set php_package for postgres
  set_fact:
    php_packages: "{{ php_packages }} + ['{{ php_prefix }}-pgsql']"
  when: dbengine == 'postgres'

- name: Set php_package for mysql
  block:
    - set_fact:
        php_packages: "{{ php_packages }} + ['{{ php_prefix }}-mysql']"
    - set_fact:
        moodle_database: "{{ moodle_database | combine({ 'dbtype': 'mariadb'}) }}"
  when: dbengine == 'mysql'
