---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Install dependencies.
  package: name={{ item }}
  with_items:
    - curl
    - unzip
    - sendmail

- name: Add repository for Apache 2.4.9+ (Ubuntu 14).
  apt_repository: repo='ppa:ondrej/apache2'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty"

- name: Add repository for PHP 7.0 (Ubuntu).
  apt_repository: repo='ppa:ondrej/php'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version != "16.04"

- name: Set php_packages for all distributions
  block:
    - set_fact:
        php_packages: []
    - set_fact:
        php_prefix: php
    - set_fact:
        php_prefix: php7.0
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - set_fact:
        php_packages: "{{ php_packages }} + [ '{{ php_prefix }}-{{ item }}' ]"
      with_items:
        - cli
        - common
        - curl
        - gd
        - intl
        - json
        - mbstring
        - mcrypt
        - opcache
        - pgsql
        - readline
        - soap
        - xml
        - xmlrpc
        - zip
        - fpm

- name: Set php_packages for PHP 7.0 Debian 8 install.
  set_fact:
    php_packages: "{{ php_packages }} + ['php-apcu']"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Need to add php-process so we can use moodle moosh
- name: Set php_packages for PHP CentOS/Redhat from REMI package.
  set_fact:
    php_packages: "{{ php_packages }} + ['php-pecl-apcu', 'php-process']"
  when: ansible_os_family == "RedHat"

- name: Copy initctl_faker into place for Ubuntu 14.04.
  copy:
    src: initctl_faker
    dest: /sbin/initctl
    mode: 0755
    force: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
  changed_when: false

- name: Define postgresql_version to 9.3 for RedHat/CentOS.
  set_fact:
    postgresql_version: "9.3"
  when: ansible_os_family == "RedHat"

- name: Set php_package for postgres
  set_fact:
    php_packages: "{{ php_packages }} + ['{{ php_prefix }}-pgsql']"
  when: dbengine == 'postgres'

- name: debug
  debug:
        msg: "System {{ moodle_database }} "

- name: Set php_package for mysql
  block:
    - set_fact:
        php_packages: "{{ php_packages }} + ['{{ php_prefix }}-mysql']"
    - set_fact:
        moodle_database: "{{ moodle_database | combine({ 'dbtype': 'mariadb'}) }}"
  when: dbengine == 'mysql'

- name: Tweak Centos package names
  block:
    - set_fact:
        mysql_packages:
          - mariadb
          - mariadb-server
          - mariadb-libs
          - MySQL-python
          - perl-DBD-MySQL
    - set_fact:
        mysql_daemon: mariadb
    - set_fact:
        mysql_log_error: /var/log/mariadb/mariadb.log
    - set_fact:
        mysql_syslog_tag: mariadb
    - set_fact:
        mysql_syslog_tag: /var/run/mariadb/mariadb.pid
  when: ansible_os_family == 'RedHat'

# https://blogs.oracle.com/jsmyth/apparmor-and-mysql
# We need a way to disable apparmor for mysql

## Specific for debian 9: we need to install mariadb at least 1.10
## as previous version are not compatible with moodle 3.0+

- name: Add repository for MariaDB (Debian) and set packages to mariadb
  block:
    - apt: name={{ item }} state=present
      with_items:
      - apt-utils
      - dirmngr
      - software-properties-common
    - apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF1656F24C74CD1D8 state=present
    - apt_repository:
        repo : deb [arch=amd64,i386,ppc64el] http://mariadb.mirrors.ovh.net/MariaDB/repo/10.3/debian stretch main
        state : present
    - set_fact:
        mysql_packages:
          - mariadb-client
          - mariadb-server
          - python-mysqldb
  when: ansible_distribution == "Debian" and ansible_distribution_release == "stretch"
