---

php_enable_webserver: false
php_enablerepo: "remi,remi-php71"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ moodle_domain_name }}"
    serveralias: "www.{{ moodle_domain_name }}"
    documentroot: "{{ moodle_src_path }}"
    extra_parameters: |
          <FilesMatch \.php$>
            SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
          </FilesMatch>

mysql_enablerepo: "remi"

postgresql_databases:
  - name: "{{ moodle_database.dbname }}"
    encoding: UTF8
    collation: en_US.UTF-8

postgresql_users:
  - name: "{{ moodle_database.dbuser }}"
    password: "{{ moodle_database.dbpass }}"
    db: "{{ moodle_database.dbname }}"

mysql_databases:
  - name: "{{ moodle_database.dbname }}"
    encoding: UTF8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ moodle_database.dbuser }}"
    host: "%"
    password: "{{ moodle_database.dbpass }}"
    priv: "{{ moodle_database.dbname }}.*:ALL"

dbengine: "mysql"

patch_to_apply:
  - aurora


moodle_version: "MOODLE_34_STABLE" # Tag or branch name

# Moodle database details
moodle_database:
  dbtype: "mariadb"
  dbhost: "localhost"
  dbname: "moodle"
  dbuser: "username"
  dbpass: "password"
  dbprefix: "mdl_"
