---

- name: Run update
  command: >
    php admin/cli/upgrade.php --non-interactive
  args:
    chdir: "{{ moodle_src_path }}"
  become: true
  become_user: "{{ moodle_webserver_user }}"
  register: updaterresult
  changed_when: updaterresult.rc != 0
