---
- name: Create a temporary directory for database dump
  ansible.builtin.tempfile:
    state: directory
    suffix: moodle_db_dump
  register: temp_dump_dir
  delegate_to: localhost

- name: Perform Moodle database dump
  block:
    - name: Install necessary packages for Postgres dump
      package:
        name:
          - postgresql-client
          - python3-psycopg2
          - libpq-dev
        state: present
      when: ansible_facts["distribution"] == 'Debian' and dbengine == 'postgres'

    - name: Install necessary packages for MySQL dump
      package:
        name:
          - python3-pymysql
        state: present
      when: ansible_facts["distribution"] == 'Debian' and dbengine == 'mysql'

    - name: Dump MySQL database
      community.mysql.mysql_db:
        name: "{{ moodle_database.dbname }}"
        login_host: "{{ moodle_database.dbhost }}"
        login_user: "{{ moodle_database.dbuser }}"
        login_password: "{{ moodle_database.password }}"
        state: dump
        target: "{{ temp_dump_dir.path }}/dump.sql"
      when: dbengine == 'mysql'

    - name: Dump PostgreSQL database
      community.postgresql.postgresql_db:
        name: "{{ moodle_database.dbname }}"
        login_host: "{{ moodle_database.dbhost }}"
        login_user: "{{ moodle_database.dbuser }}"
        login_password: "{{ moodle_database.password }}"
        state: dump
        target: "{{ temp_dump_dir.path }}/dump.sql"
      become: true
      become_user: "{{ postgresql_user }}"
      when: dbengine == 'postgres'

    - name: Compress the database dump
      archive:
        path: "{{ temp_dump_dir.path }}/dump.sql"
        dest: "{{ temp_dump_dir.path }}/dump.sql.gz"
        format: gz
        force_archive: true
      delegate_to: localhost

    - name: Fetch database dump
      fetch:
        src: "{{ temp_dump_dir.path }}/dump.sql.gz"
        dest: "dumps/moodledata-{{ inventory_hostname }}.{{ ansible_date_time.epoch }}.tar.gz"
        flat: true

  rescue:
    - name: Debug - Database dump process failed, cleaning up
      ansible.builtin.debug:
        msg: "An error occurred during the database dump. Cleaning up temporary files."

  always:
    - name: Cleanup temporary directory
      file:
        state: absent
        path: "{{ temp_dump_dir.path }}"
      delegate_to: localhost
