---

- name: Moodle- Check before if installation directory exists
  stat:
    path: "{{ moodle_src_path }}/config.php"
  register: moodle_config_source

- name: Run installer
  command: >
    php admin/cli/install_database.php
    --adminuser="{{ moodle_site_admin.username }}"
    --adminpass="{{ moodle_site_admin.password }}"
    --adminemail="{{ moodle_site_admin.email }}"
    --agree-license
    --fullname="{{ moodle_site_fullname }}"
    --shortname="{{ moodle_site_shortname }}"
  args:
    chdir: "{{ moodle_src_path }}"
  become: true
  become_user: "{{ moodle_webserver_user }}"
  register: installerresult
  changed_when: installerresult.rc != 0
  when: moodle_config_source.stat.exists|bool
