---
# Fetch moodle source from a git repository
- name: Install or update Moodle source code in the destination folder
  git:
    repo: "{{ moodle_git_url }}"
    dest: "{{ moodle_src_path }}"
    version: "{{ moodle_version }}"
    depth: 1  # Only shallow cloning. Can be fixed if needed later to have the full history (git pull --unshallow)
    key_file: "{{ moodle_git_key_file }}"
    accept_hostkey: true
    recursive: true
    update: true
    force: "{{ moodle_force_source_update }}"
    umask: "0022"
  become: true
  become_user: "{{ moodle_webserver_user }}"  # Check out as www-data
  register: moodle_git_checkout
