---
php_enable_webserver: false
php_version: '7.2'
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
mysql_python_package_debian: python3-mysqldb


apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ moodle_domain_name }}"
    serveralias: "www.{{ moodle_domain_name }}"
    documentroot: "{{ moodle_src_path }}"
    extra_parameters: |
      <FilesMatch \.php$>
        SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
      </FilesMatch>
