---
# As the playbook create the user first, we need to do that in this order
postgresql_users:
  - name: "username"
    password: "password"

postgresql_databases:
  - name: "moodle"
    owner: "username"
# Here we drop the collation info as it is an issue with CentOS/Redhat images for testing.
# TODO: find a way to install them in CENTOS 8
# https://github.com/geerlingguy/ansible-role-postgresql/blob/master/molecule/default/converge.yml

dbengine: postgres
