---
name: CI
'on':
  pull_request:
  push:
  schedule:
    - cron: "0 4 * * 4"

defaults:
  run:
    working-directory: 'call_learning.moodle'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'call_learning.moodle'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Install test dependencies.
        run: pip3 install yamllint nose ansible

      - name: Lint code.
        run: |
          yamllint .
      - name: Nose test
        run: |
          nosetests library/test_check_moodle.py
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: centos
            version: 7
            playbook: converge.yml
          - distro: debian
            version: 10
            playbook: converge.yml
          - distro: debian
            version: 11
            playbook: converge.yml
          - distro: ubuntu
            version: 2004
            playbook: converge.yml
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'call_learning.moodle'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule tests.
        run: molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_DISTRO_VERSION: ${{ matrix.version }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
