---
name: Lint
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 4"

defaults:
  run:
    working-directory: 'call_learning.moodle'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'call_learning.moodle'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible

      - name: Lint code.
        run: |
          yamllint .

