---
name: Moodle Edge
'on':
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"

jobs:
  molecule:
    name: Moodle Edge
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2404
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up uv.
        uses: astral-sh/setup-uv@v4

      - name: Install test dependencies.
        run: uv sync --frozen --python 3.12

      - name: Run Molecule tests.
        run: uv run molecule test -s default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOODLE_VERSION: "MOODLE_${{ vars.MOODLE_EDGE_VERSION || '502' }}_STABLE"
          MOODLE_RELEASE_PREFIX: '5.2.'
