---
name: CI Test
'on':
  pull_request:
  push:
  schedule:
    - cron: "0 4 * * 4"

defaults:
  run:
    working-directory: 'call_learning.moodle'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - distro: rockylinux
            version: 9
            playbook: converge.yml
          - distro: debian
            version: 12
            playbook: converge.yml
          - distro: ubuntu
            version: 2204
            playbook: converge.yml
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'call_learning.moodle'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      # See: https://github.com/geerlingguy/ansible-role-mysql/issues/422
      - name: Disable AppArmor on Debian.
        run: |
            set -x
            sudo apt-get install apparmor-profiles
            sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
            sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        if: ${{ startsWith(matrix.distro, 'debian') }}

      - name: Run Molecule tests.
        run: molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_DISTRO_VERSION: ${{ matrix.version }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
