---
name: CI Test
'on':
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 4"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2404
          - debian13
          - rockylinux9
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      # See: https://github.com/geerlingguy/ansible-role-mysql/issues/422
      - name: Disable AppArmor on Debian.
        run: |
            set -x
            sudo apt-get install apparmor-profiles
            sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
            sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        if: ${{ startsWith(matrix.distro, 'debian') }}

      - name: Run Molecule tests.
        run: molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
